CREATE TABLE COUNTRY
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  CONSTRAINT UQ_COUNTRY UNIQUE (NAME)
);

CREATE TABLE REGION
(
  ID      INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME    VARCHAR(255)                       NOT NULL,
  COUNTRY INTEGER                            NOT NULL,
  CONSTRAINT UQ_REGION UNIQUE (NAME, COUNTRY),
  CONSTRAINT FK_REGION_COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRY (ID)
);

CREATE TABLE CITY
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  COUNTRY INTEGER NOT NULL,
  REGION INTEGER,
  NAME VARCHAR(255) NOT NULL,
  CONSTRAINT FK_CITY_COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRY (ID),
  CONSTRAINT FK_CITY_REGION FOREIGN KEY (REGION) REFERENCES REGION (ID),
  CONSTRAINT UQ_CITY UNIQUE (REGION, NAME)
);

CREATE TABLE SCHOOLTYPE
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  CONSTRAINT UQ_SHOOLTYPE UNIQUE (NAME)
);

CREATE TABLE SCHOOL
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(500) NOT NULL,
  NUMBER INTEGER NULL,
  TYPE INTEGER NOT NULL,
  CITY INTEGER NOT NULL,
  CONSTRAINT FK_SCHOOL_TYPE FOREIGN KEY (TYPE) REFERENCES SCHOOLTYPE (ID),
  CONSTRAINT FK_SCHOOL_CITY FOREIGN KEY (CITY) REFERENCES CITY (ID),
  CONSTRAINT UQ_SCHOOL UNIQUE (CITY, NAME)
);


DROP TABLE SCHOOL;
DROP TABLE SCHOOLTYPE;
DROP TABLE CITY;
DROP TABLE REGION;
DROP TABLE COUNTRY;