name: gradle-ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: prepare-gradle
        run: chmod +x gradlew
      - name: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: unit-test
        run: ./gradlew :scat:check :scat:jacocoTestReport --console=plain